In [4]:
#Numpy
#it is extension package for multi dimentional array.
#Numpy has many atributes in it.
import numpy as np
a=np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Using this we can do fast numerical operations. In the scence of time for creating and updating is much less in numpy
a=range(10000)
%timeit[i**2 for i in a]
b=np.arange(10000)
%timeit b**2
#9.71 microSecond is musch lesser than 3.87 milisecond

3.87 ms ± 60.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
9.71 µs ± 501 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
#check dimension of given array
a = np.array([[1,2,3],[4,5,0]])
print(a)
print(a.ndim)  
a.shape

[[1 2 3]
 [4 5 0]]
2


(2, 3)

In [28]:
# we can create array of n-dimension as well..... 
a=np.array([[1,2,3],[4,5,6],[7,8,9],[14,25,36]])
print(a)
print(a.ndim)
print(a.shape)
# 1D arrays are called as Vector
# 2D arrays are called as matrix
# nD arrays are called as tensors

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [14 25 36]]
2
(4, 3)


In [30]:
# Commonly used arrays
# matrix of all 1's
a=np.ones((3,3))
print(a)
#Zero matrix
a=np.zeros((3,3))
print(a)
#Identity matrix
a=np.eye(3)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
a=np.diag([1,2,3,1])
print(a)
# datatype can also be sent as a parameter 

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 1]]


In [36]:
# slicing : Similar to list, Strings only
a=np.arange(10)
print(a[0:5])

[0 1 2 3 4]


In [38]:
#Updating values in array
a=np.array([[1,0,2],[2,5,7]])
print(a)
print("Update 1,1")
a[1,1]=9
print(a)

[[1 0 2]
 [2 5 7]]
Update 1,1
[[1 0 2]
 [2 9 7]]


In [39]:
#Combine assignment and slicing
a=np.arange(10)
a[0:5]=10
print(a)


[10 10 10 10 10  5  6  7  8  9]


In [43]:
# For memory optimiszation numpy points to same memory address
a=np.arange(5)
b=np.array([1,2,3,4,5])
c=a[0:2]
print(np.may_share_memory(a,b))
print(np.may_share_memory(a,c))
# c and a are pointing to same memory location only so updating c will update a only.
#Numpy thinks that any slice has been created for temporary use only

False
True


In [44]:
# fancy indexing can also be done. We can have slices indexing an integer as well as a bolean or integer arrays.
#using this we can control the way we want to write a code.

In [47]:
# Opeartions on numpy
# With Scalars we can do any basic operations like addition, multiplication etc. 
a=np.array([1,2,3,4])
a=a+1
print(a)
a=a*2;
print(a)

[2 3 4 5]
[ 4  6  8 10]


In [54]:
#Element wise additon, subtrction, multiplication between two arrays.
a=np.array([1,2,3,4,5,6])
b=np.arange(6)
print(a+b)
print(a-b)
print(a*b)
#element wise comparsion can also be done
print(a==b)

[ 1  3  5  7  9 11]
[1 1 1 1 1 1]
[ 0  2  6 12 20 30]
[False False False False False False]


In [55]:
# Matrix multiplication
c=np.diag([1,21,3,4])
# matrix multiplication is damm easy. Just go like below
print(c*c)
print("**************")
print(c.dot(c))
c=np.diag([1,21,3,9])
print(a==b)

[[  1   0   0   0]
 [  0 441   0   0]
 [  0   0   9   0]
 [  0   0   0  16]]
**************
[[  1   0   0   0]
 [  0 441   0   0]
 [  0   0   9   0]
 [  0   0   0  16]]
[False False False False False False]


In [80]:
# Mathematical functions sin,cos etc
a=np.arange(5)
print(np.sin(a))
# this cosine function is very usefull later we have to deal with his.
print(np.cos(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


C:\Users\Temp\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


In [65]:
# numpy has also sum,max,min, these function for 1D array and sum(axis=0||axis=1) for n dimensional
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Vertical addition","//","Column wise")
print(a.sum(axis=0))
print("Horizontal addtion","//","Row wise")
a.sum(axis=1)

Vertical addition // Column wise
[12 15 18]
Horizontal addtion // Row wise


array([ 6, 15, 24])

In [69]:
# Satatistics
a=np.array([1,5,9,3,6,8])
print("Min")
print(np.min(a))
print("Sum")
print(np.sum(a))
print("Max")
print(np.max(a))
print("Mean")
print(np.mean(a))
print("median")
print(np.median(a))
print("std")
print(np.std(a))

Min
1
Sum
32
Max
9
Mean
5.333333333333333
median
5.5
std
2.748737083745107


In [74]:
#Broadcasting: It is an important concept in numpy that accept any diemnsional tensors and add it with any other dimensional array.
a=np.arange(3)
a=a.T #To take a transpose
b=np.array([[1,2,3],[4,5,6]])
print("printing a ******")
print(a)
print("printing b *******")
print(b)
print("Printing a+b: ****")
print(a+b)

printing a ******
[0 1 2]
printing b *******
[[1 2 3]
 [4 5 6]]
Printing a+b: ****
[[1 3 5]
 [4 6 8]]


In [ ]:
# reshape is a cool function used to reshape an array into a matrix

In [79]:
# sorting data row wise
a=np.array([[5,61,7],[1,20,3]])
b=np.sort(a,axis=1)
print(b)
print("Or we can go with: in place sort")
a.sort()
print(a)

[[ 5  7 61]
 [ 1  3 20]]
Or we can go with: in place sort
[[ 5  7 61]
 [ 1  3 20]]
